### ISSUE TITLE
Add more responsive goodness :pie:

### ISSUE THREAD

**Issue by parkr** [jglovier/gifs#17]
Not sure how you'd like to approach this problem (or whether you see it as a problem) from a design standpoint:

![screen shot 2014-02-07 at 5 47 55 pm](https://f.cloud.github.com/assets/237985/2118766/4a2d3162-911f-11e3-985f-e17f6245bce3.png)

How should each fold? Does the sidebar become a small header then each category is listed below in a box of the white color but flush to the edges?

**Comment by jglovier** [comment]
Finally did this in https://github.com/jglovier/gifs/commit/f37d6f932a777064572fa1f89367b5a042385e4d
